chromosomes: 'all'
L: 50
runs:
  #static: ''
  #0-5: 'random.sample(idx[:5],k=5)' #all shasta
  #5-10: 'random.sample(idx[5:],k=5)' #all hifiasm
  #10-20: 'random.sample(idx,k=len(idx))' #randomly shuffled
  #20-40: '[i+random.randint(0,1)*5 for i in range(0,5,1)]' #randomly pick hifi/shasta per pair
  #300-310: 'random.sample([0,3,4,5,8,9],k=6)' 
    
  5-10: 'random.sample(idx,k=len(idx))' #random shuffle
  
assemblies:
  ARS: '/cluster/work/pausch/alex/REF_DATA/ARS-UCD1.2_Btau5.0.1Y.fa'
  B_hifiasm: 'assemblies/BSW.hifiasm.fasta'
  O_hifiasm: 'assemblies/obv.hifiasm.fasta'
  H_hifiasm: 'assemblies/ob1.hifiasm.fasta'
  Os1_hifiasm: 'assemblies/ob1.hifiasm.fasta'
  Os2_hifiasm: 'assemblies/ob1.hifiasm.fasta'
  Od1_hifiasm: 'assemblies/ob1.hifiasm.fasta'
  Od2_hifiasm: 'assemblies/ob1.hifiasm.fasta'
  B31_hifiasm: 'assemblies/ob1.hifiasm.fasta'
  B32_hifiasm: 'assemblies/ob1.hifiasm.fasta'
  B41_hifiasm: 'assemblies/ob1.hifiasm.fasta'
  B42_hifiasm: 'assemblies/ob1.hifiasm.fasta'
  H_clr:     'assemblies/Highland.fa'
  A_clr:     'assemblies/Angus.fa'
  P_hifiasm: 'assemblies/pied.hifiasm.fasta'
  S_ont: 'assemblies/pied.hifiasm.fasta' #manual
