## Pangenome panel
reference: reference.fa

assemblies:
  asm1:
    - asm1.hap1.fa
    - asm1.hap2.fa
  asm2:
    - asm2.hap1.fa
    - asm2.hap1.fa
  asm3:
    - asm3.hap1.fa
    - asm3.hap2.fa
trios:
  asm1:
    - asm2
    - asm3

scripts: '<dir>'
mscripts: '<dir>'
outdir: 'pangenie_panel/'
frac_missing: .15

## Pangenome genotyping
small_variants: DV.vcf.gz

## Pangenie stuff
#panel: '/cluster/work/pausch/alex/eQTL_GWAS/pangenie_panel.vcfwave.vcf'
fastq: ''

HiFi:
  sample1: hifi_1.fq.gz
  sample2: hifi_2.fq.gz

#pangenie_out: '/cluster/work/pausch/alex/eQTL_GWAS/pangenie_wave/samples.all.pangenie_genotyping.vcf.gz'

## Phasing and imputation
#beagle4: ''
beagle5: ''
window: 10000000
overlap: 20000


samples:
  - sample1
  - sample2

## molecular QTL mapping
#variants:
#  PanGenie: '/cluster/work/pausch/alex/eQTL_GWAS/pangenie_8_wave/samples.all.pangenie_genotyping_DV.vcf.gz'
#  SR: '/cluster/work/pausch/alex/eQTL_GWAS/variants/DV-SR/cohort.autosomes.WGS.imputed.vcf.gz'

covariates:
  eQTL:
    Testis: 'eQTL.covar'
  sQTL:
    Testis: 'sQTL.covar'

permutations: 2500
window: 1000000 #1 Mb
chunks: 40
