

## Pangenome panel
reference: reference.fa

assemblies:
  asm1:
    - asm1.hap1.fa
    - asm1.hap2.fa
  asm2:
    - asm2.hap1.fa
    - asm2.hap1.fa
  asm3:
    - asm3.hap1.fa
    - asm3.hap2.fa
trios:
  asm1:
    - asm2
    - asm3

scripts: '<dir>'
mscripts: '<dir>'
outdir: 'pangenie_panel/'
frac_missing: .15

## Pangenome genotyping
DV-SR: '/cluster/work/pausch/alex/eQTL_GWAS/variants/DV-SR/cohort.autosomes.WGS.vcf.gz'

## Pangenie stuff
panel: '/cluster/work/pausch/alex/eQTL_GWAS/pangenie_panel.vcfwave.vcf'
fastq: '/cluster/work/pausch/alex/eQTL_GWAS/fastq/'

pangenie_out: '/cluster/work/pausch/alex/eQTL_GWAS/pangenie_wave/samples.all.pangenie_genotyping.vcf.gz'

## Phasing and imputation
beagle4: '/cluster/work/pausch/alex/software/beagle.27Jan18.7e1.jar'
beagle5: '/cluster/work/pausch/alex/software/beagle.22Jul22.46e.jar'
window: 10000000
overlap: 20000


samples:
  - sample1
  - sample2

## molecular QTL mapping
variants:
  PanGenie: '/cluster/work/pausch/alex/eQTL_GWAS/pangenie_8_wave/samples.all.pangenie_genotyping_DV.vcf.gz'
  SR: '/cluster/work/pausch/alex/eQTL_GWAS/variants/DV-SR/cohort.autosomes.WGS.imputed.vcf.gz'

covariates:
  eQTL:
    Testis: '/cluster/work/pausch/xena/eQTL/cis_all/testis/testis_covariates.txt'
  sQTL:
    Epi: '/cluster/work/pausch/xena/eQTL/sQTL/epi_h/removed/QTLtools/epi_sQTL_covariates.txt'
    Testis: '/cluster/work/pausch/xena/eQTL/sQTL/testis/removed/QTLtools/sQTL_covariates_removed_testis.txt'
    Vas_d: '/cluster/work/pausch/xena/eQTL/sQTL/vas_d/removed/QTLtools/sQTL_covariates_vas_d.txt'

permutations: 2500
window: 1000000 #1 Mb
chunks: 40
