name: snakemaker
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: snakemake
        uses: snakemake/snakemake-github-action@v1.25.1
        with:
          directory: '.test'
          args: '--dryrun'
